/red:
  ros__parameters:
    class_name: red
    hue_min0: 0
    hue_max0: 1
    hue_min1: 0
    hue_max1: 255
    sat_min0: 3
    sat_max0: 4
    sat_min1: 1
    sat_max1: 2
    val_min0: 1
    val_max0: 0
    val_min1: 0
    val_max1: 0
    min_area: 75
/blue:
  ros__parameters:
    class_name: blue
    hue_min0: 12
    hue_max0: 14
    sat_min0: 7
    sat_max0: 20
    val_min0: 7
    val_max0: 20
    min_area: 75
/green:
  ros__parameters:
    class_name: green
    hue_min0: 3
    hue_max0: 8
    sat_min0: 0
    sat_max0: 25
    val_min0: 0
    val_max0: 25
    min_area: 75
