/red:
  ros__parameters:
    class_name: red
    hue_min0: 0
    hue_max0: 1
    hue_min1: 0
    hue_max1: 255
    sat_min0: 3
    sat_max0: 4
    sat_min1: 1
    sat_max1: 2
    val_min0: 1
    val_max0: 0
    val_min1: 0
    val_max1: 0
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/blue:
  ros__parameters:
    class_name: blue
    hue_min0: 12
    hue_max0: 14
    sat_min0: 7
    sat_max0: 20
    val_min0: 7
    val_max0: 20
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/green:
  ros__parameters:
    class_name: green
    hue_min0: 3
    hue_max0: 8
    sat_min0: 0
    sat_max0: 25
    val_min0: 0
    val_max0: 25
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/black:
  ros__parameters:
    class_name: black
    hue_min0: 95
    hue_max0: 180
    sat_min0: 23
    sat_max0: 100
    val_min0: 21
    val_max0: 92
    min_area: 40
    max_area: 500
    wh_ratio: 1.4
    hw_ratio: 1.5
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66