/red:
  ros__parameters:
    class_name: red
    upper_hsv1: 10
    upper_hsv2: 255
    upper_hsv3: 255
    upper_hsv4: 180
    upper_hsv5: 255
    upper_hsv6: 255
    lower_hsv1: 0
    lower_hsv2: 100
    lower_hsv3: 100
    lower_hsv4: 160
    lower_hsv5: 100
    lower_hsv6: 100
    min_area: 75
/blue:
  ros__parameters:
    class_name: blue
    upper_hsv1: 130
    upper_hsv2: 255
    upper_hsv3: 255
    lower_hsv1: 100
    lower_hsv2: 50
    lower_hsv3: 50
    min_area: 75
/green:
  ros__parameters:
    class_name: green
    upper_hsv1: 85
    upper_hsv2: 255
    upper_hsv3: 255
    lower_hsv1: 35
    lower_hsv2: 50
    lower_hsv3: 50
    min_area: 75
