/red:
  ros__parameters:
    class_name: red
    hue_min0: 0
    hue_max0: 6
    hue_min1: 172
    hue_max1: 180
    sat_min0: 100
    sat_max0: 255
    sat_min1: 55
    sat_max1: 255
    val_min0: 100
    val_max0: 255
    val_min1: 55
    val_max1: 255
    min_area: 50
/blue:
  ros__parameters:
    class_name: blue
    hue_min0: 110
    hue_max0: 140
    sat_min0: 80
    sat_max0: 200
    val_min0: 60
    val_max0: 200
    min_area: 50
/green:
  ros__parameters:
    class_name: green
    hue_min0: 60
    hue_max0: 90
    sat_min0: 70
    sat_max0: 255
    val_min0: 65
    val_max0: 255
    min_area: 50