/red:
  ros__parameters:
    class_name: red
    hue_min0: 0
    hue_max0: 10
    hue_min1: 160
    hue_max1: 180
    sat_min0: 100
    sat_max0: 255
    sat_min1: 100
    sat_max1: 255
    val_min0: 100
    val_max0: 255
    val_min1: 100
    val_max1: 255
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/blue:
  ros__parameters:
    class_name: blue
    hue_min0: 125
    hue_max0: 140
    sat_min0: 70
    sat_max0: 200
    val_min0: 70
    val_max0: 200
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/green:
  ros__parameters:
    class_name: green
    hue_min0: 35
    hue_max0: 85
    sat_min0: 50
    sat_max0: 255
    val_min0: 50
    val_max0: 255
    min_area: 75
    max_area: 500
    wh_ratio: 1.4
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
/black:
  ros__parameters:
    class_name: black
    hue_min0: 95
    hue_max0: 180
    sat_min0: 23
    sat_max0: 100
    val_min0: 21
    val_max0: 92
    min_area: 40
    max_area: 500
    wh_ratio: 1.4
    hw_ratio: 1.5
    upper_limit_boundary: 0.33
    lower_limit_boundary: 0.66
