/red:
  ros__parameters:
    class_name: red
    hue_min0: 0
    hue_max0: 10
    hue_min1: 160
    hue_max1: 180
    sat_min0: 100
    sat_max0: 255
    sat_min1: 100
    sat_max1: 255
    val_min0: 100
    val_max0: 255
    val_min1: 100
    val_max1: 255
    min_area: 75
/blue:
  ros__parameters:
    class_name: blue
    hue_min0: 125
    hue_max0: 140
    sat_min0: 70
    sat_max0: 200
    val_min0: 70
    val_max0: 200
    min_area: 75
/green:
  ros__parameters:
    class_name: green
    hue_min0: 35
    hue_max0: 85
    sat_min0: 50
    sat_max0: 255
    val_min0: 50
    val_max0: 255
    min_area: 75
