waypoints:
  - waypoint_1:
      x: 1.0   # 1 meter in the X direction
      y: 2.0   # 2 meters in the Y direction
      z: 0.0   # 0.5 meters in the Z direction
  - waypoint_2:
      x: 2.5   # 2.5 meters in the X direction
      y: 3.0   # 3 meters in the Y direction
      z: 0.0   # Ground level
  - waypoint_3:
      x: 3.5   # 3.5 meters in the X direction
      y: 1.0   # 1 meter in the Y direction
      z: 0.0   # 1 meter in the Z direction
  - waypoint_4:
      x: 4.0   # 4 meters in the X direction
      y: 4.5   # 4.5 meters in the Y direction
      z: 0.0   # 0.2 meters in the Z direction
  - waypoint_5:
      x: 5.0   # 5 meters in the X direction
      y: 0.0   # On the Y axis (no offset)
      z: 0.0   # Ground level
