task:
  ros__parameters:
    wait_time: 100 # miliseconds
    global_wp_reached_rad: 3.0 # meters
    start_lat: 63.4409453 #-35.3632222
    start_lon: 10.4199125 #149.1654373
    finish_lat: -35.3632622
    finish_lon: 149.1652373
maneuvering:
  ros__parameters:
    distance_to_move: 10.0 # meters
    angle_from_buoys: 10.0 # degrees
    wp_reached_radius: 1.0 #meters
    camera_res_x: 1920
    camera_fov: 70