task:
  ros__parameters:
    wait_time: 100 # miliseconds
    global_wp_reached_rad: 3.0 # meters
    start_lat: 63.26480 #-35.3632222
    start_lon: 10.25448 #149.1654373
    finish_lat: 63.26445
    finish_lon: 10.25413
maneuvering:
  ros__parameters:
    distance_to_move: 30.0 # meters
    angle_from_buoys: 20.0 # degrees
    wp_reached_radius: 1.0 #meters
    camera_res_x: 640
    camera_fov: 70
    wait_time: 1.0 # seconds
    testing_angles: 0
    test_angle: 90.0
    finish_lat: 63.4411718
    finish_lon: 10.4237096
    red_buoy_label: "hi"
    green_buoy_label: "how"
    second_red_buoy_label: "are"
    second_green_buoy_label: "you"
collision_avoidance:
  ros__parameters:
    finish_lat: 63.44090
    finish_lon: 10.42370
    min_dist: 0.01
    max_dist:  5.0
    fov: 30.0 # +/- from 90 degrees on each side, i.e. if fov = 20, fov is from 70 to 110
    obstacle_length: 2.0
    obstacle_length_range: 0.5
    mode_when_obstacles: 1 # 0 for hold, 1 for loiter, 2 for manual
wp_sender:
  ros__parameters:
    dist: 11.0
