task:
  ros__parameters:
    wait_time: 100 # miliseconds
    global_wp_reached_rad: 3.0 # meters
    start_lat: -35.3633545
    start_lon: 149.1653442
    finish_lat: -35.3632621
    finish_lon: 149.1652374
maneuvering:
  ros__parameters:
    distance_to_move: 10.0 # meters
    angle_from_buoys: 10.0 # degrees
    wp_reached_radius: 1.0 #meters
    camera_res_x: 1920
    camera_fov: 70