task:
  ros__parameters:
    wait_time: 100 # miliseconds
    global_wp_reached_rad: 3.0 # meters
    start_lat: -35.3633545
    start_lon: 149.1653442
    finish_lat: -35.3632621
    finish_lon: 149.1652374
