segmentation:
  ros__parameters:
    distance_threshold: 0.30
    max_avg_distance_from_sensor: 20.0
    max_points_segment: 200
    max_segment_width: 10.0
    method_threshold: ''
    min_avg_distance_from_sensor: 0.0
    min_points_segment: 3
    min_segment_width: 0.2
    noise_reduction: 0.3
    restore_defaults: false
    scan_topic: scan
    segmentation_type: jump_distance_merge
    segments_topic: segments