/maneuvering:
  ros__parameters:
    distance_to_move: 20.0
    angle_from_target: 20.0
    camera_res_x: 640
    camera_fov: 70
    finish_lat: 63.4411718
    finish_lon: 10.4237096
    recovery_behaviour: STOP
    time_to_pause_search: 0.000
    time_between_recovery_actions: 2.0
    time_to_stop_before_recovery: 20.0
    red_buoy_label: red
    green_buoy_label: green
    second_red_buoy_label: black_buoy
    second_green_buoy_label: yellow_buoy
    frame_stack_size: 10
    bbox_selection: INNERMOST
    max_consec_recoveries: 2
    state: RECOVERING
/speed:
  ros__parameters:
    distance_to_move: 20.0
    angle_from_target: 20.0
    camera_res_x: 640
    camera_fov: 70
    recovery_behaviour: STOP
    red_buoy_label: red
    green_buoy_label: green
    blue_buoy_label: blue
    second_blue_buoy_label: blue_buoy
    second_red_buoy_label: black_buoy
    second_green_buoy_label: yellow_buoy
    frame_stack_size: 4
    bbox_selection: INNERMOST
    use_start_point: 0
    time_to_find_bay: 10.0
    max_time_between_bay_detections: 10.000
    max_time_between_buoy_detections: 10.0
    buoy_offset_angle: 0.0
    estimated_buoy_dist: 20.0
    buoy_circling_radius: 3.0
    num_pnts_on_semicircle: 6
    min_dist_from_bay_b4_return: 50.000
    remove_wp_within_dist: 1.2
    state: SENDING_START_PNT
/task_controller:
  ros__parameters:
    tasks: s