name: Humble Source Build
on:
 push:
    branches:
      - jo-Actions

jobs:
  humble_source:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
